import {User, Subscription, SubscriptionMember} from "@/index";
import {faker} from "@faker-js/faker";

const now = new Date()
const time = {createdAt: now, updatedAt: now}
export const users: User[] = [
  {id: '1', name: 'a', ...time},
  {id: '2', name: 'b', ...time},
  {id: '3', name: 'c', ...time},
]

export const getAccount = ({userId, accountId, providerId}) => {
  return {
    id: faker.string.uuid(),
    type: 'id',
    providerUsername: faker.person.fullName(),
    accountId,
    providerId,
    userId,
    ...time
  }
}

const accounts = [
  getAccount({userId: '1', accountId: 'test-1', providerId: 'test' }),
  getAccount({userId: '2', accountId: 'test-2', providerId: 'test' }),
  getAccount({userId: '3', accountId: 'test-3', providerId: 'test' }),
  getAccount({userId: '1', accountId: '58338', providerId: 'beatsaver' }),
  getAccount({userId: '3', accountId: '41378', providerId: 'beatsaver' }),
]

export const channels = [
  {id: '1', channelId: 'onebot:2', providerId: 'test', ...time},
  {id: '2', channelId: 'onebot:1', providerId: 'test', ...time},
  {id: '3', channelId: 'onebot:7', providerId: 'test', ...time},
]

export const subscriptionMembers: SubscriptionMember[] = [

  {memberId: '1', subscriptionId: '6', subscribeData: { }, ...time}, // 生效 58338
  {memberId: '1', subscriptionId: '7', subscribeData: { }, ...time}, // 未启用
  {memberId: '1', subscriptionId: '8', subscribeData: { }, ...time}, // 生效 58338


  // 未绑定账户
  {memberId: '2', subscriptionId: '6', subscribeData: { }, ...time}, // 未绑定
  {memberId: '2', subscriptionId: '7', subscribeData: { }, ...time}, // 未启用，未绑定
  {memberId: '2', subscriptionId: '8', subscribeData: { }, ...time}, // 未绑定
  // 未加入7,8
  {memberId: '3', subscriptionId: '6', subscribeData: { }, ...time}, // 生效 41378
]
export const subscriptions: Subscription[] = [
  { id: 'bsmap::1::58338', type: 'bsmap', eventType:'bsmap-update', enabled: true, channelId: '1', data: { mapperId: '58338' }, ...time },
  { id: '6', type: 'bsmap-group', eventType:'bsmap-update', enabled: true, channelId: '1', data: null, ...time },
  { id: '7', type: 'bsmap-group', eventType:'bsmap-update', enabled: false, channelId: '2', data: null, ...time },
  { id: '8', type: 'bsmap-group', eventType:'bsmap-update', enabled: true, channelId: '3', data: null, ...time },
]

export const mockData = {
  users,
  channels,
  accounts,
  subscriptions,
  subscriptionMembers,
  sess: {
    user: users[0],
    channel: channels[0],
    mentions: [],
    locale: 'zh-CN'
  }
}


export const getBeatSaverMapEvent = (mapperId: string, mapId: string) => ({
  type: 'MAP_UPDATE',
  msg: {
    id: mapId,
    name: '夢をみせて',
    description: '',
    uploader: {
      id: mapperId,
      name: 'chiikawa_._.',
      uniqueSet: true,
      avatar:
        'https://cdn.beatsaver.com/avatar/54d3f024ab3eede26b5f4344ef51fc7e9b297d2f.png',
      type: 'DISCORD',
      admin: false,
      curator: false,
      seniorCurator: false,
      curatorTab: false,
      verifiedMapper: false,
      playlistUrl: 'https://api.beatsaver.com/users/id/202666/playlist',
    },
    metadata: {
      bpm: 120,
      duration: 325,
      songName: '夢をみせて',
      songSubName: '',
      songAuthorName: 'Cö shu Nie',
      levelAuthorName: 'Beat Sage',
    },
    stats: {
      plays: 0,
      downloads: 0,
      upvotes: 0,
      downvotes: 0,
      score: 0.5,
      reviews: 0,
      sentiment: 'PENDING',
      scoreOneDP: 50,
    },
    uploaded: '2024-05-06T11:40:43.687478Z',
    automapper: true,
    ranked: false,
    qualified: false,
    versions: [
      {
        hash: '3297d14f7d56576b91c31e922e08f643a9000185',
        state: 'Published',
        createdAt: '2024-05-06T11:40:06.959435Z',
        sageScore: -14,
        diffs: [
          {
            njs: 10,
            offset: 0,
            notes: 220,
            bombs: 10,
            obstacles: 9,
            nps: 0.752,
            length: 585.019,
            characteristic: 'Standard',
            difficulty: 'Normal',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 292.509,
            paritySummary: {
              errors: 53,
              warns: 29,
              resets: 0,
            },
            maxScore: 195155,
          },
          {
            njs: 10,
            offset: 0,
            notes: 400,
            bombs: 23,
            obstacles: 17,
            nps: 1.317,
            length: 607.598,
            characteristic: 'Standard',
            difficulty: 'Hard',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 303.799,
            paritySummary: {
              errors: 48,
              warns: 31,
              resets: 0,
            },
            maxScore: 360755,
          },
          {
            njs: 12,
            offset: 0,
            notes: 460,
            bombs: 57,
            obstacles: 26,
            nps: 1.454,
            length: 632.74,
            characteristic: 'Standard',
            difficulty: 'Expert',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 316.37,
            paritySummary: {
              errors: 23,
              warns: 12,
              resets: 18,
            },
            maxScore: 415955,
          },
          {
            njs: 16,
            offset: 0,
            notes: 664,
            bombs: 71,
            obstacles: 48,
            nps: 2.096,
            length: 633.501,
            characteristic: 'Standard',
            difficulty: 'ExpertPlus',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 316.751,
            paritySummary: {
              errors: 13,
              warns: 10,
              resets: 11,
            },
            maxScore: 603635,
          },
          {
            njs: 10,
            offset: 0,
            notes: 164,
            bombs: 28,
            obstacles: 24,
            nps: 0.611,
            length: 537.2,
            characteristic: 'OneSaber',
            difficulty: 'Normal',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 268.6,
            paritySummary: {
              errors: 55,
              warns: 18,
              resets: 11,
            },
            maxScore: 143635,
          },
          {
            njs: 10,
            offset: 0,
            notes: 229,
            bombs: 25,
            obstacles: 32,
            nps: 0.734,
            length: 623.839,
            characteristic: 'OneSaber',
            difficulty: 'Hard',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 311.92,
            paritySummary: {
              errors: 48,
              warns: 27,
              resets: 3,
            },
            maxScore: 203435,
          },
          {
            njs: 12,
            offset: 0,
            notes: 442,
            bombs: 13,
            obstacles: 36,
            nps: 1.41,
            length: 626.921,
            characteristic: 'OneSaber',
            difficulty: 'Expert',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 313.461,
            paritySummary: {
              errors: 34,
              warns: 46,
              resets: 2,
            },
            maxScore: 399395,
          },
          {
            njs: 16,
            offset: 0,
            notes: 667,
            bombs: 11,
            obstacles: 55,
            nps: 2.106,
            length: 633.501,
            characteristic: 'OneSaber',
            difficulty: 'ExpertPlus',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 316.751,
            paritySummary: {
              errors: 54,
              warns: 82,
              resets: 3,
            },
            maxScore: 606395,
          },
          {
            njs: 10,
            offset: 0,
            notes: 209,
            bombs: 8,
            obstacles: 8,
            nps: 0.778,
            length: 537.2,
            characteristic: 'NoArrows',
            difficulty: 'Normal',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 268.6,
            paritySummary: {
              errors: 0,
              warns: 0,
              resets: 0,
            },
            maxScore: 185035,
          },
          {
            njs: 10,
            offset: 0,
            notes: 279,
            bombs: 21,
            obstacles: 4,
            nps: 0.894,
            length: 623.839,
            characteristic: 'NoArrows',
            difficulty: 'Hard',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 311.92,
            paritySummary: {
              errors: 0,
              warns: 0,
              resets: 0,
            },
            maxScore: 249435,
          },
          {
            njs: 12,
            offset: 0,
            notes: 507,
            bombs: 24,
            obstacles: 13,
            nps: 1.603,
            length: 632.74,
            characteristic: 'NoArrows',
            difficulty: 'Expert',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 316.37,
            paritySummary: {
              errors: 0,
              warns: 0,
              resets: 0,
            },
            maxScore: 459195,
          },
          {
            njs: 16,
            offset: 0,
            notes: 768,
            bombs: 26,
            obstacles: 18,
            nps: 2.425,
            length: 633.501,
            characteristic: 'NoArrows',
            difficulty: 'ExpertPlus',
            events: 0,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 316.751,
            paritySummary: {
              errors: 0,
              warns: 0,
              resets: 0,
            },
            maxScore: 699315,
          },
          {
            njs: 10,
            offset: 0,
            notes: 214,
            bombs: 3,
            obstacles: 4,
            nps: 0.797,
            length: 537.2,
            characteristic: '90Degree',
            difficulty: 'Normal',
            events: 16,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 268.6,
            paritySummary: {
              errors: 46,
              warns: 48,
              resets: 1,
            },
            maxScore: 189635,
          },
          {
            njs: 10,
            offset: 0,
            notes: 282,
            bombs: 3,
            obstacles: 7,
            nps: 0.904,
            length: 623.839,
            characteristic: '90Degree',
            difficulty: 'Hard',
            events: 7,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 311.92,
            paritySummary: {
              errors: 72,
              warns: 45,
              resets: 0,
            },
            maxScore: 252195,
          },
          {
            njs: 12,
            offset: 0,
            notes: 566,
            bombs: 38,
            obstacles: 16,
            nps: 1.852,
            length: 611.281,
            characteristic: '90Degree',
            difficulty: 'Expert',
            events: 18,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 305.641,
            paritySummary: {
              errors: 101,
              warns: 68,
              resets: 6,
            },
            maxScore: 513475,
          },
          {
            njs: 16,
            offset: 0,
            notes: 771,
            bombs: 34,
            obstacles: 25,
            nps: 2.434,
            length: 633.501,
            characteristic: '90Degree',
            difficulty: 'ExpertPlus',
            events: 79,
            chroma: false,
            me: false,
            ne: false,
            cinema: false,
            seconds: 316.751,
            paritySummary: {
              errors: 44,
              warns: 57,
              resets: 10,
            },
            maxScore: 702075,
          },
        ],
        downloadURL:
          'https://cdn.beatsaver.com/3297d14f7d56576b91c31e922e08f643a9000185.zip',
        coverURL:
          'https://cdn.beatsaver.com/3297d14f7d56576b91c31e922e08f643a9000185.jpg',
        previewURL:
          'https://cdn.beatsaver.com/3297d14f7d56576b91c31e922e08f643a9000185.mp3',
      },
    ],
    createdAt: '2024-05-06T11:40:06.959435Z',
    updatedAt: '2024-05-06T11:40:43.687478Z',
    lastPublishedAt: '2024-05-06T11:40:43.687478Z',
    tags: [],
    declaredAi: 'None',
  },
})
